In [80]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
digit=load_digits()

All directories of digit datasets

In [81]:
dir(digit)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [82]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(digit.data,digit.target,train_size=0.7)

Score if we use logistic regression

In [83]:
from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression()
log_reg.fit(x_train,y_train)
log_reg.score(x_test,y_test)

C:\Users\User\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.95

Score if we use random forest 

In [84]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=40)
rfc.fit(x_train,y_train)
rfc.score(x_test,y_test)

0.9703703703703703

Score if we use support vector machine

In [85]:
from sklearn.svm import SVC
svm=SVC(gamma='auto')
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.42407407407407405

In [86]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=5)
kf

KFold(n_splits=5, random_state=None, shuffle=False)

Firstly KFold(data) works with index,not actual values.So here it splites them by their position not values

devided the datasets into n_splits times,first part goes for train dataset,second part goes to test datasets

In [87]:
for train_i,test_i in kf.split([1,2,3,4,5,6,7,8,9,10]):
    print(train_i,test_i)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [88]:
def get_accuracy(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [89]:
get_accuracy(SVC(),x_train,x_test,y_train,y_test)

0.9851851851851852

StratifiedKFold is used in machine learning to ensure that the distribution of classes in each fold matches the distribution of classes in the overall dataset.

In [ ]:
from sklearn.model_selection import StratifiedKFold
kf_model=StratifiedKFold(n_splits=5)

In [91]:
scores_lr=[]
scores_rf=[]
scores_svm=[]

for train_i,test_i in kf.split(digit.data):
    x_train,x_test,y_train,y_test=digit.data[train_i],digit.data[test_i],digit.target[train_i],digit.target[test_i]

    scores_lr.append(get_accuracy(LogisticRegression(),x_train,x_test,y_train,y_test))
    scores_rf.append(get_accuracy(RandomForestClassifier(),x_train,x_test,y_train,y_test))
    scores_svm.append(get_accuracy(SVC(gamma='auto'),x_train,x_test,y_train,y_test))

C:\Users\User\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_mode

In [92]:
scores_lr

[0.9277777777777778,
 0.8666666666666667,
 0.9387186629526463,
 0.935933147632312,
 0.9080779944289693]

In [93]:
scores_rf

[0.9416666666666667,
 0.9055555555555556,
 0.9554317548746518,
 0.9637883008356546,
 0.9275766016713092]

In [94]:
scores_svm

[0.4305555555555556,
 0.37777777777777777,
 0.43175487465181056,
 0.38440111420612816,
 0.5097493036211699]

In [95]:
from sklearn.model_selection import cross_val_score

In [99]:
cross_val_score(LogisticRegression(),digit.data,digit.target)

C:\Users\User\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_mode

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [100]:
cross_val_score(RandomForestClassifier(n_estimators=40),digit.data,digit.target)

array([0.925     , 0.87777778, 0.95821727, 0.96100279, 0.91086351])

In [98]:
cross_val_score(SVC(gamma='auto'),digit.data,digit.target)

array([0.41111111, 0.45      , 0.454039  , 0.44846797, 0.47910864])